"""
i18n.py — Traductions partagées pour les pages hors application
(Contact, Disclaimer). La langue est lue dans st.session_state['lang'],
définie par le sélecteur de langue de l'application.
"""

from __future__ import annotations

import streamlit as st

LANG_DEFAUT = "fr"

_DISCLAIMER_FR = """
**Plant Doctor** fournit un diagnostic généré par une **intelligence artificielle**,
à titre purement **informatif et indicatif**.

- Les résultats peuvent comporter des **erreurs** et ne remplacent pas l'avis d'un
  professionnel (pépiniériste, jardinerie, service phytosanitaire, agronome).
- N'appliquez aucun traitement (produit, engrais, pesticide…) sans vérifier son
  **adéquation, son dosage et la réglementation** en vigueur dans votre pays.
- Les **astuces de grand-mère** sont proposées à titre traditionnel et doivent être
  utilisées avec prudence.
- Aucune garantie n'est donnée quant à l'exactitude de l'identification ou des
  recommandations.
- Vos photos et analyses sont **stockées** pour constituer votre historique ; vous
  pouvez les supprimer à tout moment depuis l'application.

En utilisant l'application, vous reconnaissez que son éditeur ne saurait être tenu
responsable de tout dommage résultant de l'usage des informations fournies.
"""

_DISCLAIMER_EN = """
**Plant Doctor** provides a diagnosis generated by **artificial intelligence**,
for **informational and indicative purposes only**.

- Results may contain **errors** and do not replace the advice of a professional
  (nursery, garden centre, plant-health service, agronomist).
- Do not apply any treatment (product, fertiliser, pesticide…) without checking its
  **suitability, dosage and the regulations** in force in your country.
- **Grandma's tips** are offered as traditional remedies and should be used with care.
- No guarantee is given as to the accuracy of the identification or recommendations.
- Your photos and analyses are **stored** to build your history; you can delete them
  at any time from the application.

By using the application, you acknowledge that its publisher cannot be held liable
for any damage resulting from the use of the information provided.
"""

_DISCLAIMER_DE = """
**Plant Doctor** liefert eine von **künstlicher Intelligenz** erstellte Diagnose,
ausschließlich zu **Informations- und Orientierungszwecken**.

- Die Ergebnisse können **Fehler** enthalten und ersetzen nicht den Rat einer
  Fachperson (Gärtnerei, Gartencenter, Pflanzenschutzdienst, Agronom).
- Wenden Sie keine Behandlung (Produkt, Dünger, Pestizid…) an, ohne deren
  **Eignung, Dosierung und die geltenden Vorschriften** in Ihrem Land zu prüfen.
- **Großmutters Tipps** sind traditionelle Hausmittel und mit Vorsicht zu verwenden.
- Es wird keine Garantie für die Richtigkeit der Identifikation oder der
  Empfehlungen übernommen.
- Ihre Fotos und Analysen werden für Ihren Verlauf **gespeichert**; Sie können sie
  jederzeit in der Anwendung löschen.

Mit der Nutzung der Anwendung erkennen Sie an, dass der Herausgeber nicht für
Schäden haftet, die aus der Verwendung der bereitgestellten Informationen entstehen.
"""

_T = {
    "fr": {
        "contact_title": "## 📨 Contact",
        "contact_caption": "Une question, un problème ou une suggestion ? Écrivez-nous.",
        "contact_subject": "Sujet",
        "contact_message": "Message",
        "contact_send": "Envoyer",
        "contact_empty": "Veuillez saisir un message.",
        "contact_sent": "✅ Message envoyé. Merci, nous vous répondrons par e-mail.",
        "contact_fallback": "📧 Envoi automatique indisponible. Écrivez-nous directement à : **{admin}**",
        "contact_noaddr": "Aucune adresse de contact n'est configurée pour le moment.",
        "contact_no_subject": "(sans sujet)",
        "disclaimer_title": "## ⚠️ Avertissement / Disclaimer",
        "disclaimer_md": _DISCLAIMER_FR,
        "disclaimer_caption": "Diagnostic IA — à titre indicatif. En cas de doute, consultez un professionnel.",
    },
    "en": {
        "contact_title": "## 📨 Contact",
        "contact_caption": "A question, an issue or a suggestion? Write to us.",
        "contact_subject": "Subject",
        "contact_message": "Message",
        "contact_send": "Send",
        "contact_empty": "Please enter a message.",
        "contact_sent": "✅ Message sent. Thank you, we'll reply by email.",
        "contact_fallback": "📧 Automatic sending unavailable. Write to us directly at: **{admin}**",
        "contact_noaddr": "No contact address is configured at the moment.",
        "contact_no_subject": "(no subject)",
        "disclaimer_title": "## ⚠️ Disclaimer",
        "disclaimer_md": _DISCLAIMER_EN,
        "disclaimer_caption": "AI diagnosis — for guidance only. If in doubt, consult a professional.",
    },
    "de": {
        "contact_title": "## 📨 Kontakt",
        "contact_caption": "Eine Frage, ein Problem oder ein Vorschlag? Schreiben Sie uns.",
        "contact_subject": "Betreff",
        "contact_message": "Nachricht",
        "contact_send": "Senden",
        "contact_empty": "Bitte geben Sie eine Nachricht ein.",
        "contact_sent": "✅ Nachricht gesendet. Vielen Dank, wir antworten per E-Mail.",
        "contact_fallback": "📧 Automatischer Versand nicht verfügbar. Schreiben Sie uns direkt an: **{admin}**",
        "contact_noaddr": "Derzeit ist keine Kontaktadresse konfiguriert.",
        "contact_no_subject": "(kein Betreff)",
        "disclaimer_title": "## ⚠️ Haftungsausschluss",
        "disclaimer_md": _DISCLAIMER_DE,
        "disclaimer_caption": "KI-Diagnose — nur als Orientierung. Im Zweifel einen Fachmann fragen.",
    },
}


def current_lang() -> str:
    return st.session_state.get("lang", LANG_DEFAUT)


def tr(key: str, **kw) -> str:
    lang = current_lang()
    s = _T.get(lang, _T["fr"]).get(key) or _T["fr"].get(key, key)
    return s.format(**kw) if kw else s
